name: Nightly Performance Test

on:
  workflow_dispatch:
  schedule:
    - cron: "30 18 * * *"

jobs:    
  nightly-load-test:
    name: Nightly Load Test 
    runs-on: ubuntu-latest 
    permissions:
      contents: write   
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 
        uses: actions/setup-python@v2 
        with:
          python-version: '3.x'
          
      - name: Install ChromeDriver and Chrome
        run: |
          # Download and install Chrome 114
          wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/114.0.5735.90/linux64/chrome-linux64.zip
          unzip chrome-linux64.zip
          sudo mv chrome-linux64/chrome /usr/local/bin/google-chrome
          sudo chmod +x /usr/local/bin/google-chrome
          
          # Install ChromeDriver 114
          wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/114.0.5735.90/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          
          # Install required dependencies for Chrome
          sudo apt-get update
          sudo apt-get install -y libnss3 libgconf-2-4 libfontconfig1
          
          # Verify installations
          google-chrome --version
          chromedriver --version
      
      - name: Install dependencies 
        run: |
           python -m pip install --upgrade pip
           pip install -r perftest/requirements.txt 
      
      - name: Load Test
        run: |
          python perftest/load_time.py
