name: Nightly Performance Test

on:
  workflow_dispatch:
  schedule:
    - cron: "30 18 * * *"

jobs:    
  nightly-load-test:
    name: Nightly Load Test 
    runs-on: ubuntu-latest 
    permissions:
      contents: write   
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 
        uses: actions/setup-python@v2 
        with:
          python-version: '3.x'
          
      - name: Install ChromeDriver and Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.69/linux64/chromedriver-linux64.zip
          unzip chromedriver_linux64.zip -d /usr/local/bin
          sudo apt-get install -y google-chrome-stable

          
          # Verify installations
          google-chrome --version
          chromedriver --version
      
      - name: Install dependencies 
        run: |
           python -m pip install --upgrade pip
           pip install -r perftest/requirements.txt 
      
      - name: Load Test
        run: |
          python perftest/load_time.py
