name: Nightly Performance Test

on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * *"

jobs:    
  nightly-load-test:
    name: Nightly Load Test 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 
        uses: actions/setup-python@v2 
        with:
          python-version: '3.x'
      
      - name: Install dependencies 
        run: |
           pip install -r perftest/requirements.txt 
           npm install -g artillery
      
      - name: Load Test
        run : python perftest/load_time.py
      
      - name: Run Artillery Load Test
        run: artillery run perftest/load-test.yml --output perftest/load_report.json
      
      - name: Upload Load Test Results
        uses: actions/upload-artifact@v3
        with :
           name: load-test-results 
           path : perftest/load_report.json 
