name: Nightly Performance Test

on:
  workflow_dispatch:
  schedule:
    - cron: "30 18 * * *"

jobs:    
  nightly-perf-test:
    name: Nightly Perf Test 
    runs-on: ubuntu-latest 
    permissions:
      contents: write   
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 
        uses: actions/setup-python@v2 
        with:
          python-version: '3.x'
          
      - name: Install ChromeDriver and Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://storage.googleapis.com/chrome-for-testing-public/131.0.6778.69/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip -d /usr/local/bin
          sudo apt-get install -y google-chrome-stable

          
          # Verify installations
          google-chrome --version
          chromedriver --version
      
      - name: Install dependencies 
        run: |
           python -m pip install --upgrade pip
           pip install -r perftest/requirements.txt 
           npm install -g artillery
      
      - name: Load Time
        run: |
          python perftest/load_time.py
          
      - name: Run Artillery Load Test
        run: |
          artillery run --target  https://cs455-assignment-load-balancer.onrender.com perftest/load-test.yml --output perftest/report_server.json
          artillery run --target  https://cs455-project.github.io/CS455-Assignment-1 perftest/load-test.yml --output perftest/report_game.json


      - name: Convert report to html format
        run: |
          artillery report -o perftest/load_test_report_server.html perftest/report_server.json
          artillery report -o perftest/load_test_report_game.html perftest/report_game.json
      
      - name: Upload Perf Test Results
        uses: actions/upload-artifact@v4
        with :
           name: load-test-results 
           path : |
             perftest/load_test_report_server.html
             perftest/load_test_report_game.html
             performance_reports
