name: Nightly Performance Test

on:
  workflow_dispatch:
  schedule:
    - cron: "30 18 * * *"

jobs:    
  nightly-load-test:
    name: Nightly Load Test 
    runs-on: ubuntu-latest 
    permissions:
      contents: write   
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 
        uses: actions/setup-python@v2 
        with:
          python-version: '3.x'
          
      - name: Install ChromeDriver and Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://chromedriver.storage.googleapis.com/$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip -d /usr/local/bin
          sudo apt-get install -y google-chrome-stable

          
      - name: Install dependencies 
        run: |
           pip install -r perftest/requirements.txt 
           npm install -g artillery
      
      - name: Load Test
        run: |
          python perftest/load_time.py
        # env:
        #   DISPLAY: :99
      
      - name: Run Artillery Load Test
        run: artillery run perftest/load-test.yml --output perftest/load_report.json

      - name: Convert report to html format
        run: artillery report -o perftest/load_report.html perftest/load_report.json
      
      - name: Upload Load Test Results
        uses: actions/upload-artifact@v3
        with :
           name: performance-results 
           path : |
             perftest/load_report.html 
             perftest/performance_reports
