name: Nightly Performance Test

on:
  workflow_dispatch:
  schedule:
    - cron: "30 18 * * *"

jobs:    
  nightly-load-test:
    name: Nightly Load Test 
    runs-on: ubuntu-latest 
    permissions:
      contents: write   
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 
        uses: actions/setup-python@v2 
        with:
          python-version: '3.x'
          
      - name: Install ChromeDriver and Chrome
        run: |
          # Install Chrome 114 (specific version)
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.5735.198-1_amd64.deb
          sudo apt install ./google-chrome-stable_114.0.5735.198-1_amd64.deb
          
          # Install ChromeDriver 114
          wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
          
          # Verify installations
          google-chrome --version
          chromedriver --version
      
      - name: Install dependencies 
        run: |
           python -m pip install --upgrade pip
           pip install -r perftest/requirements.txt 
      
      - name: Load Test
        run: |
          python perftest/load_time.py
