name: Nightly Performance Test

on:
  workflow_dispatch:
  schedule:
    - cron: "30 18 * * *"

jobs:    
  nightly-load-test:
    name: Nightly Load Test 
    runs-on: ubuntu-latest 
    permissions:
      contents: write   
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 
        uses: actions/setup-python@v2 
        with:
          python-version: '3.x'
          
      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      
      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | cut -d ' ' -f3 | cut -d '.' -f1)
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          curl -L -o chromedriver.zip "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin/
          chromedriver --version
          
      - name: Install dependencies 
        run: |
           pip install -r perftest/requirements.txt 
           npm install -g artillery
      
      - name: Load Test
        run : python perftest/load_time.py
        env:
          CHROME_BINARY_PATH: /usr/bin/google-chrome
          DISPLAY: :99
      
      - name: Run Artillery Load Test
        run: artillery run perftest/load-test.yml --output perftest/load_report.json

      - name: Convert report to html format
        run: artillery report -o perftest/load_report.html perftest/load_report.json
      
      - name: Upload Load Test Results
        uses: actions/upload-artifact@v3
        with :
           name: load-test-results 
           path : perftest/load_report.html 
      
      - name: Upload Load Time Results
        uses: actions/upload-artifact@v3
        with :
           name: load-time-results 
           path : perftest/performance_reports
